apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: iproduct:1.0-SNAPSHOT
    name: iproduct-container
    env:
    - name: PRODUCT_TEMP
      value: "/Output/Temp"
    ports:
    - containerPort: 8090
      hostPort: 8090
    volumeMounts:
    - mountPath: /Output/Temp
      name: temp
  volumes:
  - name: temp
    hostPath:
      # directory location on host
      path: /host_mnt/c/iwork/OutputFile
